version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.4

workflows:
  default:
    jobs:
      - test
      - build-docs:
          requires:
            - test
          filters: &filtdoc
            branches:
              only: 
                - master
                - develop
                - circleci-editor/develop
      - deploy-github-pages:
          requires:
            - build-docs
          filters: *filtdoc


jobs:
  test:
    docker: &pydocker
      # - image: cimg/python:3.8
        - image: tjlaboss/centos7-dakota6.14:0.0.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: &pypkg
            /usr/bin/pip3
      - run:
          name: Run tests
          command: ./run_tests.sh

  build-docs:
    docker: *pydocker
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: *pypkg
          pip-dependency-file: doc/requirements.txt
      - run:
          name: Build docs
          command: cd doc && ./build_docs.sh
      - persist_to_workspace:
          root: doc/_build
          paths:
            - html

  deploy-github-pages:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: doc/_build
      - run:
          name: Survey the project directory.
          command: ls -Rlhr
      - run:
          name: Install gh-pages dependency
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@tjla.boston"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "32:a1:57:b9:74:55:55:dd:a5:f7:b7:3f:0b:50:85:20"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist doc/_build/html
