version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

workflows:
  default:
    jobs:
      - test
      - build-docs:
          requires:
            - test
          filters: &filtdoc
            branches:
              only: 
                - master
                - develop
      - deploy-github-pages:
          requires:
            - build-docs
          filters: *filtdoc


jobs:
  test:
    docker: &pydocker
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: ./run_tests.sh

  build-docs:
    docker: *pydocker
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: doc/requirements.txt
      - run:
          name: Build docs
          command: cd doc && ./build_docs.sh
      - persist_to_workspace:
          root: doc/_build
          paths:
            - html

  deploy-github-pages:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: doc/_build
      - run:
          name: Survey the project directory.
          command: ls -Rlhr
      - run:
          name: Install gh-pages dependency
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@tjla.boston"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "5d:b9:a4:70:b7:36:0f:e8:88:44:9a:d9:4e:5b:38:ee"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist doc/_build/html
